name: Run Apify Pull

permissions:
  contents: write

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Microsoft ODBC driver
        run: |
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18 unixodbc-dev

      - run: pip install -r requirements.txt

      - run: python script/getwar3races.py

      - name: Commit race pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add script/war3cs2_pages

          git commit -m "Update race pages" || echo "No changes"

          git push
      
      - run: python script/fetch_apify.py
        env:
          APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          AZURE_SQL_SERVER: ${{ secrets.AZURE_SQL_SERVER }}
          AZURE_SQL_DATABASE: ${{ secrets.AZURE_SQL_DATABASE }}
          AZURE_SQL_USERNAME: ${{ secrets.AZURE_SQL_USERNAME }}
          AZURE_SQL_PASSWORD: ${{ secrets.AZURE_SQL_PASSWORD }}
          
