name: Run Apify Pull

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - run: python script/apify_pull.py
        env:
          APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
